version: "3.8"

volumes: 
  mongodb_volume:

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - 27017:27017
    volumes: 
      - mongodb_volume:/data/db
    restart: always

  app:
    build: ./app
    container_name: app
    hostname: app
    ports: 
      - 5000:5000
    restart: always
    depends_on:
      - mongodb
      - rabbit
    environment: 
      - TZ=Europe/Moscow
      - DISCOURSE_API_KEY=
      - SECRET_AUTH_TOKEN=
